name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t chippu17 .
        
      - name: Push Docker image to Docker Hub (or other registry)
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag your-docker-image-name your-docker-username/your-docker-image-name:latest
          docker push your-docker-username/your-docker-image-name:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull and run Docker container
        run: |
          docker pull your-docker-username/your-docker-image-name:latest
          docker run -d -p 3000:3000 your-docker-username/your-docker-image-name:latest
