name: Node.js CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with: { node-version: 18, cache: npm }
      - run: npm install

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cat-tournament:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - run: docker run -d --pull always -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/cat-tournament
